customProperty: customProperty

redis.server: 127.0.0.1
redis.port: 6379

spring:
  jpa:
    database: MYSQL
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/springhealth_intervention
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver